services:
  # Redis service for bot state management
  redis:
    image: redis:8.2-alpine
    container_name: gornbot-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - gornbot-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Telegram bot application
  bot:
    build: .
    container_name: gornbot-app
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml:ro
    networks:
      - gornbot-network
    healthcheck:
      test: ["CMD", "python", "health_check.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  redis_data:
    driver: local

networks:
  gornbot-network:
    driver: bridge
