services:
  # Redis service for bot state management (PROD)
  redis:
    image: redis:8.2-alpine
    container_name: gornbot-redis-prod
    restart: unless-stopped
    ports:
      - "6379:6379"  # Standard Redis port for production
    volumes:
      - redis_data_prod:/data
    command: redis-server --appendonly yes
    networks:
      - gornbot-network-prod
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Telegram bot application (PROD)
  bot:
    build: .
    container_name: gornbot-app-prod
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - TZ=Europe/Moscow
      - ENVIRONMENT=prod
    volumes:
      - ./logs:/app/logs  # Production logs directory
      - ./config.yaml:/app/config.yaml:ro
    networks:
      - gornbot-network-prod
    healthcheck:
      test: ["CMD", "python", "health_check.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  redis_data_prod:
    driver: local

networks:
  gornbot-network-prod:
    driver: bridge
